Renaming of datadog agent and packaging
StackVista/sts-agent pull request #2
Opened 2016-09-22 13:27 UTC by craffit

2016-09-22 18:10 UTC, kostyanich commented on CHANGELOG.md
>  * Configuring checks in datadog.conf for checks.d is deprecated and won't work anymore. Please configure your checks by editing the yaml files in the conf.d directory.
datadog.conf. please check if CHANGELOG.md goes to package

2016-09-22 18:11 UTC, kostyanich commented on README.md
>  The Datadog Agent faithfully collects events and metrics and brings
Datadog in readme

2016-09-22 18:14 UTC, kostyanich commented on checks.d/go_expvar.py
> +                                 "Please contact support@stackstate.com for more information.")
is it support@stackstate.com? or info@stackstate.com? please just double check our support url

2016-09-22 18:19 UTC, kostyanich commented on conf.d/docker.yaml.example
> +# The user running the StackState Agent (usually "dd-agent") must be part of the "docker" group
dd-agent reference

2016-09-22 18:26 UTC, kostyanich commented on config.py
>              agentConfig['use_dogstatsd'] = config.get('Main', 'use_dogstatsd').lower() in ("yes", "true")
we might have "use_stsstatsd" in configuration...

2016-09-22 18:29 UTC, kostyanich commented on packaging/datadog-agent/source/install_agent.sh
>  logfile="ddagent-install.log"
ddagent-install.log?

2016-09-22 18:33 UTC, kostyanich commented on packaging/osx/install.sh
>  logfile=ddagent-install.log
ddagent-install.log

2016-09-22 18:34 UTC, kostyanich commented on packaging/osx/install.sh
>  dmg_file=/tmp/datadog-agent.dmg
datadog-agent.dmg

2016-09-22 18:34 UTC, ktatarnikov commented on packaging/osx/install.sh
>  with the contents of ddagent-install.log and we'll do our very best to help you
ddagent-install.log

2016-09-22 18:35 UTC, kostyanich commented on packaging/osx/install.sh
> +    sudo cp '/opt/stackstate-agent/etc/com.datadoghq.agent.plist' /Library/LaunchDaemons
datadoghq

2016-09-22 19:01 UTC, kostyanich commented on stackstate.conf.example
>  # use_dogstatsd: yes
this is the property use_dogstatsd in config I reffered previously...

2016-09-22 19:04 UTC, kostyanich commented on tests/core/test_config.py
>          win_check_path = u"C:\\ProgramData\\Datadog\\conf.d\\haproxy.yaml"
Windows check path refer to Datadog

2016-09-22 19:08 UTC, ktatarnikov requested changes
please check my comments...

2016-09-23 08:42 UTC, raboof commented on tests/core/test_config.py
>          win_check_path = u"C:\\ProgramData\\Datadog\\conf.d\\haproxy.yaml"
I think we can leave windows and osx out of scope for now

2016-09-23 08:43 UTC, raboof commented on stackstate.conf.example
>  # use_dogstatsd: yes
let's discuss with @markbakker78 if we really want to rename dogstatsd and how far we want to take this

2016-09-23 08:44 UTC, raboof commented on packaging/osx/install.sh
> +    sudo cp '/opt/stackstate-agent/etc/com.datadoghq.agent.plist' /Library/LaunchDaemons
I think we can leave osx out of scope for now

2016-09-23 08:45 UTC, raboof commented on CHANGELOG.md
>  * Configuring checks in datadog.conf for checks.d is deprecated and won't work anymore. Please configure your checks by editing the yaml files in the conf.d directory.
@craffit suggests CHANGELOG doesn't make it to the package - I'll remove this change

2016-09-23 08:45 UTC, raboof commented on README.md
>  The Datadog Agent faithfully collects events and metrics and brings
I think we don't ship the README, either

2016-09-23 09:06 UTC, raboof commented on conf.d/docker.yaml.example
> +# The user running the StackState Agent (usually "dd-agent") must be part of the "docker" group
Good one, there were still a lot of these - added them to `./sts-check-naming.sh` and fixed them

2016-09-23 09:07 UTC, raboof commented on packaging/datadog-agent/source/install_agent.sh
>  logfile="ddagent-install.log"
i think we can keep installing from source out of scope for now

2016-09-23 09:08 UTC, raboof commented
Open problems:
* We removed licensing headers, I don't think we should want that. Let's check
* We have incompletely renamed dogstatsd. I think we should consider if we want to move forward with that

2016-09-23 11:56 UTC, merged