K8stopology
StackVista/sts-agent pull request #36
Opened 2017-03-28 07:39 UTC by craffit

2017-06-01 12:56 UTC, whazenberg requested changes

2017-06-01 12:56 UTC, whazenberg commented on checks.d/kubernetes_topology.py
> +    service_check_needed = True
unused.

2017-06-01 12:56 UTC, whazenberg commented on checks.d/kubernetes_topology.py
> +    SERVICE_CHECK_NAME = "kubernetes.topology_information"
unused.

2017-06-01 12:56 UTC, whazenberg commented on checks.d/kubernetes_topology.py
> +    service_check_needed = True
Either we can add a self.service_check(..) or remove the unused code.

2017-06-01 13:00 UTC, whazenberg commented
Incomplete review

2017-06-12 11:34 UTC, whazenberg requested changes

2017-06-12 11:34 UTC, whazenberg commented on checks.d/kubernetes_topology.py
> +            'url': 'http://kubernetes'
we should use the url of the instance here, which should be set in the config

2017-06-12 11:34 UTC, whazenberg commented on utils/kubernetes/kubeutil.py
> +        Retrieve the list of nodes for this cluster qurying the kublet API.
typo in qurying

2017-06-12 11:34 UTC, whazenberg commented on utils/kubernetes/kubeutil.py
> +        Retrieve the list of services for this cluster qurying the kublet API.
typo in qurying

2017-06-12 11:34 UTC, whazenberg commented on .travis.yml
> +    - k8stopology
let's remove this before merging to master

2017-06-12 11:34 UTC, whazenberg commented on conf.d/kubernetes_topology.yaml.example
> +  # The kubernetes topology check retrieves metrics from the kubernetes api.
retrieves metrics?

2017-06-12 11:54 UTC, raboof commented on checks.d/kubernetes_topology.py
> +            'url': 'http://kubernetes'
it should be unique to the cluster, not just to the instance, right?

2017-06-13 07:41 UTC, whazenberg approved these changes

2017-06-13 07:41 UTC, whazenberg commented on checks.d/kubernetes_topology.py
> +    def _flatten_dict(self, dict_of_list):
maybe move this to utils?

2017-06-13 07:41 UTC, whazenberg commented on tests/checks/mock/test_kubernetes_topology.py
> +        # print instances[0]['relations']
remove?

2017-06-13 07:47 UTC, whazenberg commented on checks.d/kubernetes_topology.py
> +    SERVICE_CHECK_NAME = "kubernetes.topology_information"
used now

2017-06-13 07:48 UTC, whazenberg commented on checks.d/kubernetes_topology.py
> +    service_check_needed = True
used now

2017-06-13 07:49 UTC, merged