Splunk deduplication with custom fields
StackVista/sts-agent pull request #49
Opened 2017-08-22 14:57 UTC by whazenberg

Previously the Splunk event and metric checks would identify records solely on `_bkt` and `_cd` fields for deduplication purposes. This PR introduces a setting, `fields_for_identification`, that let's the check's user specify which fields make a record unique, per saved search. Setting `fields_for_identification` to `[]` results in using the whole record for identification.

The default behaviour contains fields `_bkt` and `_cd`.

2017-08-24 09:45 UTC, craffit approved these changes
Ziet er goed uit, niets op aan te merken. even wachten op Kostya's praktijk test

2017-08-24 17:13 UTC, kostyanich commented on tests/checks/mock/test_splunk_event.py
> +                        "fields_for_identification": ["uid1", "uid2"]
unique_key_fields

2017-08-24 18:08 UTC, ktatarnikov requested changes
minor comment

2017-08-28 06:49 UTC, ktatarnikov approved these changes

2017-08-28 06:49 UTC, merged